import { IconType } from 'react-icons';

import {
	HiChevronUp,
	HiChevronDown,
	HiChevronRight,
	HiChevronLeft,
	HiArrowUpRight,
	HiOutlineArrowPath,
	HiCheck,
	HiMiniQuestionMarkCircle,
	HiMiniXMark,
	HiOutlineLink,
	HiExclamationTriangle,
	HiInformationCircle,
	HiExclamationCircle,
	HiCheckCircle,
	HiOutlineGlobeAlt,
	HiArrowTopRightOnSquare,
	HiEnvelope,
	HiCalendarDays,
	HiClipboard,
	HiArrowRight,
	HiSun,
	HiMoon,
	HiStar
} from "react-icons/hi2";

import {
	PiHouseDuotone,
	PiUserCircleDuotone,
	PiGridFourDuotone,
	PiBookBookmarkDuotone,
	PiImageDuotone
} from "react-icons/pi";

import {
	FaDiscord,
	FaGithub,
	FaLinkedin,
	FaXTwitter,
	FaFacebook,
	FaInstagram,
	FaWhatsapp,
} from "react-icons/fa6";

import {
	SiReact,
	SiJavascript,
	SiTypescript,
	SiNextdotjs,
	SiTailwindcss,
	SiSass,
	SiNodedotjs,
	SiExpress,
	SiGraphql,
	SiPython,
	SiPostgresql,
	SiMongodb,
	SiRedis,
	SiMysql,
	SiSupabase,
	SiVercel,
	SiDocker,
	SiNginx,
	SiGoogleanalytics,
	SiGoogletagmanager,
	SiLighthouse,
	SiGithubactions,
	SiAmazonwebservices,
	SiJsonwebtokens,
} from "react-icons/si";

export const iconLibrary: Record<string, IconType> = {
	chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
	chevronRight: HiChevronRight,
	chevronLeft: HiChevronLeft,
	refresh: HiOutlineArrowPath,
	arrowUpRight: HiArrowUpRight,
	check: HiCheck,
	arrowRight: HiArrowRight,
	helpCircle: HiMiniQuestionMarkCircle,
	infoCircle: HiInformationCircle,
	warningTriangle: HiExclamationTriangle,
	errorCircle: HiExclamationCircle,
	checkCircle: HiCheckCircle,
	email: HiEnvelope,
	globe: HiOutlineGlobeAlt,
	person: PiUserCircleDuotone,
	grid: PiGridFourDuotone,
	book: PiBookBookmarkDuotone,
	close: HiMiniXMark,
	openLink: HiOutlineLink,
	calendar: HiCalendarDays,
	home: PiHouseDuotone,
	gallery: PiImageDuotone,
	discord: FaDiscord,
	github: FaGithub,
	linkedin: FaLinkedin,
	x: FaXTwitter,
	facebook: FaFacebook,
	instagram: FaInstagram,
	whatsapp: FaWhatsapp,
	clipboard: HiClipboard,
	arrowUpRightFromSquare: HiArrowTopRightOnSquare,
	sun: HiSun,
	moon: HiMoon,
	star: HiStar,
	// Tech / brand icons for skills
	react: SiReact,
	javascript: SiJavascript,
	typescript: SiTypescript,
	nextjs: SiNextdotjs,
	tailwindcss: SiTailwindcss,
	sass: SiSass,
	nodejs: SiNodedotjs,
	express: SiExpress,
	graphql: SiGraphql,
	python: SiPython,
	postgresql: SiPostgresql,
	mongodb: SiMongodb,
	redis: SiRedis,
	mysql: SiMysql,
	supabase: SiSupabase,
	vercel: SiVercel,
	docker: SiDocker,
	nginx: SiNginx,
	googleanalytics: SiGoogleanalytics,
	googletagmanager: SiGoogletagmanager,
	lighthouse: SiLighthouse,
	githubactions: SiGithubactions,
	aws: SiAmazonwebservices,
	jwt: SiJsonwebtokens,
};